
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["377 378 1", "377 378 2", "377 378 3", "377 378 4", "377 378 5", "377 378 6", "377 378 7", "377 378 8", "377 378 9", "377 378 10", "377 378 11", "377 378 12", "377 378 13", "377 378 14", "377 378 15", "377 378 16", "377 378 17", "377 378 18", "377 378 19", "377 378 20", "377 378 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
